#! /bin/bash -e
if [ "$1" == "purge" ] && [ -e /usr/share/debconf/confmodule ] ; then
. /usr/share/debconf/confmodule
db_purge
fi
usermod -G $(groups $(id 1000 | cut -d '(' -f2 | cut -d ')' -f1) | sed 's/kelvin//')
groupdel kelvin
